.\" Project		: AntzBBB
.\" Hardware Version	: 2.0
.\" Research Group	: Massively Distributed Robotics Group
.\" Lab			: Distributed Multi-Agent Laboratory
.\" Department		: Electrical Engineering and Computer Science
.\" University		: Syracuse University, Syracuse, NY

.\" This man page documents one of the APIs of one of the subsystems of
.\" Antz Robots.


.TH IIT_ALL_SEGMENTS 3 "03-22-2016" "LCD" "version 1.0"
.SH NAME
init_all_segments - initializes all the segments the screen
.SH SYNOPSIS
.B #include <lcd.h>
.sp
.BI "void init_all_segments()"

.SH DESCRIPTION
.B init_all_segments()
is a function that lits up all the segments on screen.

.SH "SEE ALSO"
.BR lcd_init(3)
.BR lcd_deinit(3)
.BR clrscr(3)
.BR invert_color(3)
.BR lcd_write_cmd(3)
.BR lcd_write_data(3)
.BR lcd_printf(3)

.SH AUTHOR
.B Nachiket Kulkarni <npkulkar@syr.edu>

.SH COLOPHON
This page is a part documentation of release 1.0 of AntzBBB project. Other man
pages, source code and documentation can be found at 
.I https://github.com/nachiketkulkarni/AntzBBB.
