.\" Project		: AntzBBB
.\" Hardware Version	: 2.0
.\" Research Group	: Massively Distributed Robotics Group
.\" Lab			: Distributed Multi-Agent Laboratory
.\" Department		: Electrical Engineering and Computer Science
.\" University		: Syracuse University, Syracuse, NY

.\" This man page documents one of the APIs of one of the subsystems of
.\" Antz Robots.


.TH LCD_DEINIT 3 "03-22-2016" "LCD" "version 1.0"
.SH NAME
lcd_deinit() - destructor of lcd subsystem
.SH SYNOPSIS
.B #include <lcd.h>
.sp
.BI "void lcd_deinit()"

.SH DESCRIPTION
.B lcd_deinit()
is a destructor function of lcd subsystem of Antz robots.This 
function closes all the open files and must be called by the application in
their destructor routines.

.SH "SEE ALSO"
.BR lcd_init(3)
.BR clrscr(3)
.BR invert_color(3)
.BR init_all_segments(3)
.BR lcd_write_cmd(3)
.BR lcd_write_data(3)
.BR lcd_printf(3)

.SH AUTHOR
.B Nachiket Kulkarni <npkulkar@syr.edu>

.SH COLOPHON
This page is a part documentation of release 1.0 of AntzBBB project. Other man
pages, source code and documentation can be found at 
.I https://github.com/nachiketkulkarni/AntzBBB.
