.\" Project		: AntzBBB
.\" Hardware Version	: 2.0
.\" Research Group	: Massively Distributed Robotics Group
.\" Lab			: Distributed Multi-Agent Laboratory
.\" Lab Director	: Dr. Jae Oh (jcoh@syr.edu)
.\" Department		: Electrical Engineering and Computer Science
.\" University		: Syracuse University, Syracuse, NY

.\" This man page documents one of the APIs of one of the subsystems of
.\" Antz Robots.

.TH MOVE_BACKWORD 3 "03-22-2016" "DC MOTOR" "version 1.0"
.SH NAME
move_backword() - move the robot backword

.SH SYNOPSIS
.B #include "motor.h"
.sp
.BI "void move_backword(char *speed)"

.SH DESCRIPTION
.B move_backword()
is a function that drives the robot backword with the specified speed. 
.nf
The value of speed can be one of the following:
.in +8n 
.nf
.B * MT_SUPERFAST
.B * MT_FAST
.B * MT_NORMAL
.B * MT_SLOW
.B * MT_SUPERSLOW

.SH "SEE ALSO"
.BR motor_init(3)
.BR motor_deinit(3)
.BR move_forward(3)
.BR set_speed(3)
.BR set_direction(3)
.BR turn_left(3)
.BR turn_right(3)
.BR stop(3)

.SH AUTHOR
.B Nachiket Kulkarni <npkulkar@syr.edu>

.SH COLOPHON
This page is a part documentation of release 1.0 of AntzBBB project. Other man
pages, source code and documentation can be found at 
.I https://github.com/nachiketkulkarni/AntzBBB.
