.\" Project		: AntzBBB
.\" Hardware Version	: 2.0
.\" Research Group	: Massively Distributed Robotics Group
.\" Lab			: Distributed Multi-Agent Laboratory
.\" Lab Director	: Dr. Jae Oh (jcoh@syr.edu)
.\" Department		: Electrical Engineering and Computer Science
.\" University		: Syracuse University, Syracuse, NY

.\" This man page documents one of the APIs of one of the subsystems of
.\" Antz Robots.

.TH TURN_RIGHT 3 "03-22-2016" "DC MOTOR" "version 1.0"
.SH NAME
turn_right() - turn the robot to right

.SH SYNOPSIS
.B #include "motor.h"
.sp
.BI "void turn_right()"

.SH DESCRIPTION
.B turn_right()
this function turns the robot to right by 90 degrees.

.SH BUGS
.B * Turning happens at a constant slow speed. It needs to be improvised.
.nf
.B * After turning is completed, the robot speed needs to be restored to what it was before taking the turn.
.nf
.B * Angle of turn is not precise.

.SH "SEE ALSO"
.BR motor_init(3)
.BR motor_deinit(3)
.BR move_forward(3)
.BR move_backward(3)
.BR set_direction(3)
.BR set_speed(3)
.BR turn_left(3)
.BR stop(3)

.SH AUTHOR
.B Nachiket Kulkarni <npkulkar@syr.edu>

.SH COLOPHON
This page is a part documentation of release 1.0 of AntzBBB project. Other man
pages, source code and documentation can be found at 
.I https://github.com/nachiketkulkarni/AntzBBB.
